version: "3.9"


services:
  gumai_db:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
      # a way of mapping dirs from our system into the docker container This will allow it to auto sync in real time!!!
    volumes:
      - ./GumaiDB:/gumai_db
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - POSTGRES_DB=devdb 
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
      - EMAIL_USER=gumedelwazi44@gmail.com
      - EMAIL_PASS=tocupajrnnbvocng
      - DEBUG=1
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data: