version: "3.9"


services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
      # a way of mapping dirs from our system into the docker container. This will allow it to auto sync in real time!!!
    volumes:
      - /app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"